### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by yandrew** [darthvader1925/RocketLeagueBoostReplica#1]
jk...

I see you're pretty active on your github. Congrats on having 792 commits in the past year so far, way more than me. 

You should try using linux for development. Its a different OS (operating system) which you can install a bunch of other apps. The guide lets you dual boot so you can keep chrome os. 

I found a guide for installing Ubuntu (linux distribution) on chrome os: 
https://tutorials.ubuntu.com/tutorial/install-ubuntu-on-chromebook#0
the tutorial seems pretty easy to follow. It uses Crouton to help install ubuntu. 

More info here:

https://github.com/dnschneid/crouton

**Comment by HTMLstar1325** [comment]
![image](https://user-images.githubusercontent.com/46640763/71374479-b49ce480-256f-11ea-8ca0-9536eedbf20b.png)

**Comment by HTMLstar1325** [comment]
See that

**Comment by HTMLstar1325** [comment]
I have had linux for a while now

**Comment by HTMLstar1325** [comment]
![image](https://user-images.githubusercontent.com/46640763/71374632-4573c000-2570-11ea-9164-646768723e93.png)

**Comment by darthvader1925** [comment]
Woah! I was weird back then
